/**
 * @description This file contains the settings and wordlist for the game.
 * Modify variables here to change the game settings.
 * @warning Do not modify the variable names.
 * @warning BE CAUTIOUS WHILE MODIFYING VALUES OF COLUMN HEIGHT AND WIDTH. MAY CAUSE UI ISSUES.
 */

export const attempts = 5; // default 5

export const columnHeight = 17; // default 17

export const wordColumnWidth = 12; // default 12

export const dudLength = 8; // default 8

export const difficulty = 7; // default 7

export const haikus = [
	"Out of memory.<br />We wish to hold the whole sky,<br />But we never will.",
	"Three things are certain:<br />Death, taxes, and lost data.<br />Guess which has occurred.",
	"wind catches lily<br />scatt'ring petals to the wind:<br />segmentation fault",
	"The fence is for you<br />To protect you from danger<br />Don't go past the fence",
	"Joe Roquefort: hero<br />of cryptanalysis in<br />the Second World War.",
	"Math gurus showed us<br />some hash weaknesses. Panic<br />ensues. New hash now!",
	"Two thousand seven,<br />NIST says 'New hash contest now!'<br />Five years later, done.",
];

export const wordList = [
	"ABIDE",
	"BISON",
	"CLOVE",
	"DRAFT",
	"EPOCH",
	"FLARE",
	"GLINT",
	"HOVER",
	"IMBUE",
	"JOKER",
	"KNAVE",
	"LORRY",
	"MIRTH",
	"NAVEL",
	"OPINE",
	"PLUMB",
	"QUASH",
	"RAVEL",
	"SCOUT",
	"TWINE",
	"UPEND",
	"VIGOR",
	"WHIRL",
	"XENON",
	"YIELD",
	"ZONED",
	"AMONG",
	"BRINE",
	"CRISP",
	"DEFER",
	"ENEMY",
	"FABLE",
	"GRATE",
	"HAZEL",
	"INERT",
	"JELLY",
	"KINKY",
	"LEMON",
	"MOTEL",
	"NINJA",
	"OZONE",
	"PRIZE",
	"QUILL",
	"REIGN",
	"SHOVE",
	"TRUST",
	"URBAN",
	"VAPID",
	"WOUND",
	"XYSTI",
	"YACHT",
	"ZAPPY",
	"AGREE",
	"BLAST",
	"COAST",
	"DOUBT",
	"EMBER",
	"FJORD",
	"GUILD",
	"HONEY",
	"ICING",
	"JUMPY",
	"KRAUT",
	"LEVEL",
	"MANGO",
	"NEEDY",
	"OBESE",
	"PENNY",
	"QUACK",
	"RADIO",
	"STING",
	"THROB",
	"ULTRA",
	"VIXEN",
	"WALTZ",
	"XENIA",
	"YAWNS",
	"ZEBRA",
	"ALOFT",
	"BAYOU",
	"CHURN",
	"DRANK",
	"ELBOW",
	"FETCH",
	"GROAN",
	"HUMID",
	"INDEX",
	"JUROR",
	"KAPPA",
	"LOGIC",
	"MINUS",
	"NOBLE",
	"ONION",
	"PAUSE",
	"QUART",
	"ROBIN",
	"SWIRL",
	"THREE",
	"UNCUT",
	"VOUCH",
];
